fx_version('cerulean')
game('gta5')
lua54 'on'
this_is_a_map 'yes'

data_file 'DLC_ITYP_REQUEST' 'stream/atc1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/billandtv1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/billandtv2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/increasedprops_def.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/newprop.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swabrams.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swbase1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swbase2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swbase3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swbasket3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swhescowall3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swhescowall4.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swhmmwv.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swm978.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor02.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor03.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor04.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor05.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor06.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor07.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor08.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor09.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor10.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor11.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swmonitor12.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swpatriot.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swsandbagline1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swsandbagline5.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swsign01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swsign03.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swsign04.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/swsign6.ytyp' 
data_file 'DLC_ITYP_REQUEST' 'stream/swtent.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/testbuggy.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv5.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv6.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv7.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv8.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv9.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv10.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv11.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv12.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv13.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv4.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv14.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv15.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tv16.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/usbill.ytyp'
