fx_version 'cerulean'
game { 'gta5' }
author 'BzZz'
description 'Bzzz - Colored weeds pack'
version '2.0.0'


data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_weed_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_melon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_tomato_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_strawberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plant_salad_and_pumpkin.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_potato_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_garden_plant_carrot.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_onion_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_greenhouse.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_eggplant_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_plants_cucumber_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_prop_garden_lysohlavky.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_tree_pack.ytyp'