Config = Config or {}

Config.CoreName = 'qb-core' -- Change this if you changed the core name.
Config.NVItem = 'black_quad_helmet' -- Item needed to use nightvision
Config.NVItem2 = 'moss_quad_helmet' -- Item needed to use nightvision
Config.NVItem3 = 'brown_quad_helmet' -- Item needed to use nightvision
Config.NVItem4 = 'white_quad_helmet' -- Item needed to use nightvision
Config.NVItem5 = 'leopard_quad_helmet' -- Item needed to use nightvision
Config.NVItem6 = 'brown_digital_quad_helmet' -- Item needed to use nightvision
Config.NVItem7 = 'tiger_quad_helmet' -- Item needed to use nightvision
Config.NVItem8 = 'aqua_camo_quad_helmet' -- Item needed to use nightvision
Config.NVItem9 = 'splinter_quad_helmet' -- Item needed to use nightvision
Config.NVItem10 = 'brushstroke_quad_helmet' -- Item needed to use nightvision
Config.NVItem11 = 'black_red_quad_helmet' -- Item needed to use nightvision
Config.NVItem12 = 'zebra_quad_helmet' -- Item needed to use nightvision
Config.NVItem13 = 'pink_camo_quad_helmet' -- Item needed to use nightvision
Config.NVItem14 = 'desert_quad_helmet' -- Item needed to use nightvision
Config.NVItem15 = 'black_dual_helmet' -- Item needed to use nightvision
Config.NVItem16 = 'moss_dual_helmet' -- Item needed to use nightvision
Config.NVItem17 = 'brown_dual_helmet' -- Item needed to use nightvision
Config.NVItem18 = 'white_dual_helmet' -- Item needed to use nightvision
Config.NVItem19 = 'leopard_dual_helmet' -- Item needed to use nightvision
Config.NVItem20 = 'brown_digital_dual_helmet' -- Item needed to use nightvision
Config.NVItem21 = 'tiger_dual_helmet' -- Item needed to use nightvision
Config.NVItem22 = 'aqua_camo_dual_helmet' -- Item needed to use nightvision
Config.NVItem23 = 'splinter_dual_helmet' -- Item needed to use nightvision
Config.NVItem24 = 'brushstroke_dual_helmet' -- Item needed to use nightvision
Config.NVItem25 = 'black_red_dual_helmet' -- Item needed to use nightvision
Config.NVItem26 = 'zebra_dual_helmet' -- Item needed to use nightvision
Config.NVItem27 = 'pink_camo_dual_helmet' -- Item needed to use nightvision
Config.NVItem28 = 'desert_dual_helmet' -- Item needed to use nightvision

Config.CheckHelmet = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet2 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet3 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet4 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet5 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet6 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet7 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet8 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet9 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet10 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet11 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet12 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet13 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet14 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet15 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet16 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet17 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet18 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet19 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet20 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet21 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet22 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet23 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet24 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet25 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet26 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet27 = true -- Check if player has nightvision helmet (clothing)
Config.CheckHelmet28 = true -- Check if player has nightvision helmet (clothing)

Config.NVKey = 'N' -- The key you want to be pressed to toggle night/thermal vision (this is the default key, players can change this key in keybinds)